name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to GCR for mgmt-infra-applayer-01-0864/hela:0.2
        uses: docker/login-action@v2
        with:
          registry: asia.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_AUTH_BGV }}

      - name: Build and push to mgmt-infra-applayer-01-0864/hela:0.2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: asia.gcr.io/mgmt-infra-applayer-01-0864/hela:0.2

      - name: Logout from GCR for mgmt-infra-applayer-01-0864/hela:0.2
        run: docker logout asia.gcr.io
