name: Build Rust Project and Upload Binary

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: org-level-runner

    steps:
      - name: Checkout Code of Hela
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build Rust project
        run: |
          cargo build --release
          echo "Contents of release directory:"
          ls -l $GITHUB_WORKSPACE/target/release

      - name: Copy binary to workspace root
        run: cp $GITHUB_WORKSPACE/target/release/Hela $GITHUB_WORKSPACE/Hela

      - name: Run the binary
        run: $GITHUB_WORKSPACE/Hela

      - name: Print contents of $GITHUB_WORKSPACE
        run: ls -l $GITHUB_WORKSPACE

      - name: Upload binary to external URL using -F option
        run: |
          curl -X POST \
            -F "file=@$GITHUB_WORKSPACE/Hela" \
            https://196c108de2230786d31a11da090098fb.m.pipedream.net
